name: Ruby

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2'
          - '3.1'
          - '3.0'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the specs
      run: ./bin/test

  build:
    # Only run if the push is a tag that starts with 'v'
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    name: Build Gem
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true
    - name: Build RubyGem
      run: gem build *.gemspec
    - name: Push RubyGem
      run: gem push *.gem
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}

